title = "Marianna Lovato"
baseURL = "https://example.com"
theme = "hugo-researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Marianna Lovato"
  description = "A simple monospaced resume theme for Hugo."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "By Marianna Lovato | Last updated: April 2021"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "200px"
    colorBlack = "#222222"
    colorRed = "#dc3545"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Research"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Teaching"
    url = "/taching"
    weight = 2
  [[menu.main]]
    name = "CV"
    url = "/resume.pdf"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
